### PR TITLE
support global vars for custom path

### PR DESCRIPTION
**Pull request by edolphin-ydf**

### CODE REVIEW

**Comment by InsaneDoggo** [comment]
Hi, thx for your request, i'll add this feature after some checks. P.S. i'm working on plugin in leisure time, so it may take few days.

**Comment by InsaneDoggo** [comment]
What did you mean by:

> it could be empty, this may means ignore this search

1. Cancel one action then continue search?
2. Cancel CustomPath and create in default path?
3. Cancel creating element (template, dir)?

**Comment by InsaneDoggo** [comment]
Here #2 u can downlaod version with your feature. Notify me if it works not as expected.
P.S. u shoud use **${DS}** for dollar sign **$**. (important for _Regex_ ).

**Comment by edolphin-ydf** [comment]
Hi, the pic below is an example, the global var ${mult} is an optional var, so it may be an empty string.
In this case, i want the plugin ignore this action and continue search the next one. If not, it will search path with an empty string and report an error `not found`. So, answer your question, i means `1. Cancel one action then continue search?`

**Comment by InsaneDoggo** [comment]
In this case your pull-request is correct, all must works fine.

**Pull request merged**
